language: go

go:
  - 1.12.x

os:
  - linux

env:
  global:
    - GO111MODULE=on


script:
  - go build -mod=vendor cmd/pwgen/main.go
  - go test -mod=vendor -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)