language: go

go:
  - 1.12.x
  - tip

os:
  - linux

env:
  global:
    - GO111MODULE=on
    - GOFLAGS='-mod vendor'


script:
  - go build cmd/pwgen/main.go
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)